### ISSUE TITLE
disableCache doesn't apply to partials

### ISSUE THREAD

**Issue by shellscape** [gilt/koa-hbs#33]
Using the disableCache option works well for primary views, but isn't respected with regard to partials. While the overhead may be high, it'd be very useful for a development environment if those were given the same consideration as primary views when disableCache is used as an option.

**Comment by shellscape** [comment]
@jwilm ping! this is still an issue, might be hard to solve, but it should be addressed in the docs at the very least.

**Comment by renaesop** [comment]
In fact， you can modify source code yourself， it's not difficult!

**Comment by shellscape** [comment]
fixed by d1e84c518c6f9e06b3be6a6ec9934cd93beb86ea
