### ISSUE TITLE
Layout overrides

### ISSUE THREAD

**Issue by geoffberger** [gilt/koa-hbs#44]
We've been using this middleware for a while now and it's worked out really well.

Unless there is already a preferred way of doing this in its current state, we wanted to add the following features:

- ability to specify the layout on a render level (I know it can be done on the template, but that unfortunately won't work for us)
- ability to render without a layout when a defaultLayout has been specified

I was able to figure out a way of doing this without modifying koa-hbs, but it's pretty hacky. In the interest of contributing for others to use, I'd be happy to put in a pull request with the changes specified above. If there is already a way of accomplishing the above that I may have missed, I'm more than open to that too.

Thanks!

**Comment by shellscape** [comment]
@geoffberger please do submit a pull request for these features.

**Comment by shellscape** [comment]
@geoffberger your first request has been fulfilled by https://github.com/gilt/koa-hbs/pull/51. closing this issue since it's gone stale. we'd be happy to take a look at a PR with changes and tests for the second request.

**Comment by geoffberger** [comment]
👍
