### ISSUE TITLE
when koa-hbs will support koa2

### ISSUE THREAD

**Issue by tonylinyy** [gilt/koa-hbs#46]
we use koa-hbs in our project,and testing  koa2
koa2 is released,when koa-hbs will support it, thanks

**Comment by shellscape** [comment]
Word has it that node v7 will be using the version of V8 that supports async/await natively, and that's what is holding up Koa v2 from exiting alpha/next status. Once that happens, we'll update koa-hbs. 

In the mean time, you can use [koa-adapter](https://www.npmjs.com/package/koa-adapter), which will allow you to use koa v1 middleware with koa v2.

**Comment by Robin-front** [comment]
has some methods to fit koa2?

**Comment by shellscape** [comment]
@Robin-front come again?
