### ISSUE TITLE
Looking for someone to take over this project

### ISSUE THREAD

**Issue by jwilm** [gilt/koa-hbs#47]
It's been a couple of years since I was using Koa, and at least a year since doing any work with Node.js. I'm not putting the time into this project that it and the developers relying on it deserve. If there's anyone interested in taking over this project, please speak up here.

Thanks to everyone who has used this project and worked to improve it.

cc @Volox @coderhaoxin @leecade @pierreinglebert @guileen @yojique @shellscape @TheEmpty

**Comment by shellscape** [comment]
https://github.com/gilt as an organization would be willing to. we use koa-hbs extensively in production.

**Comment by jwilm** [comment]
Having an organization be the steward of koa-hbs could be really good for everyone. I'm personally a fan of this option.

**Comment by coderhaoxin** [comment]
@jwilm I can also transfer this repo to [koajs](https://github.com/koajs)

**Comment by jwilm** [comment]
Moving the repo to the koa organization sounds good for the longevity of the project. Maybe @shellscape can be added as a contributor? Does that work for everyone?

**Comment by shellscape** [comment]
👍

**Comment by coderhaoxin** [comment]
@jwilm I'm outing for several days, you can transfer this repo to me, and I'll transfer it to `koajs org` later.

@shellscape Are you also willing to help maintain `koa-hbs`?

**Comment by shellscape** [comment]
@coderhaoxin yes, as are the front end developers in the gilt org. we use it quite extensively

**Comment by jwilm** [comment]
@coderhaoxin looks like you have an active fork of koa-hbs. The project can't be transferred until that's renamed/removed.

**Comment by jwilm** [comment]
@shellscape @coderhaoxin you're both collaborators for now until the repo can be moved.

**Comment by shellscape** [comment]
👍  great thanks @jwilm

**Comment by jwilm** [comment]
@shellscape maybe I should just move this to gilt?

**Comment by shellscape** [comment]
@jwilm we'd be happy to take it on. the company's npm account is gilt-tech, if you'd like to add them as a collaborator there as well.

**Comment by jwilm** [comment]
I've added `gilt-tech` on npm. Is the correct GitHub receiver simply `gilt`?

**Comment by shellscape** [comment]
yes https://github.com/gilt - it's an organization account

**Comment by jwilm** [comment]
There's a `koa-hbs` in gilt already, and it's preventing the transfer. Can you move it?

**Comment by shellscape** [comment]
Yeah that's our fork. Just renamed it to `gilt-koa-hbs`. You should be good to go!

**Comment by jwilm** [comment]
ugh. Slightly different error. Apparently you can't have anything in the koa-hbs network.

**Comment by shellscape** [comment]
@jwilm ok, we've got our last change merged in so I'll kill the repo. not a problem.

**Comment by jwilm** [comment]
The error messages associated with this process are pretty crap. I can't actually transfer it to gilt since I don't have admin rights there, but I think I can transfer it to another user. The repo could be transferred to you, and you could transfer it to gilt.

**Comment by shellscape** [comment]
@jwilm ok let's do that, no problem.

**Comment by jwilm** [comment]
Woo, finally!

> Repository transfer to shellscape requested

**Comment by shellscape** [comment]
Nice! Is there anything I have to confirm? (haven't seen anything yet)

**Comment by shellscape** [comment]
We're all set! Thanks for taking the time to push that through @jwilm .
