### ISSUE TITLE
Mising '.' in index.js, line 344

### ISSUE THREAD

**Issue by develmts** [gilt/koa-hbs#53]
It makes unable to render templates on some circumstances
As far as i can see this:
`var tplPath = path.join(viewPath, tpl + this.extname);`
should be changed to this
`var tplPath = path.join(viewPath, tpl + '.' +this.extname);`

No idea  of colateral implications, but it's disallowing me to use koa-hbs

**Comment by shellscape** [comment]
under what circumstances are you unable to render? please provide some code examples. koa-hbs has been around a while, and this is the first instance of the issue I've seen.

**Comment by develmts** [comment]
Sorry. Misunderstood the whole thing. Absolutely my mistake. Forget it and sorry for wasting your tie. Clsoing
